[project]
name = "mlflow-sweep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nicki Skafte", email = "skaftenicki@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
mlflow-sweep = "mlflow_sweep:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
