command:
  uv run example.py
  --learning-rate ${learning_rate}
  --batch-size ${batch_size}
  --parent-run-id ${parent_run_id}
experiment_name: sweep-demo
sweep_name: test-sweep
method: random
metric:
  name: accuracy
  goal: maximize
parameters:
  learning_rate:
    distribution: uniform
    min: 0.001
    max: 0.1
  batch_size:
    values: [16, 32, 64, 128]
run_cap: 10
